### ISSUE TITLE
Please clarify your position on the AGPL license

### ISSUE THREAD

**Issue by chadkirby** [winkjs/wink-bm25-text-search#13]
I was evaluating this library for use in a new (commercial/not-open-source) service, when I noticed the AGPL license, which some consider to be a 'viral' license. 

Do you believe that the AGPL requires me to open-source my software if my software uses the wink-bm25-text-search library (without making any modifications to wink-bm25)? 

Or by licensing the library under the AGPL, did you intend to allow me to use and distribute the library (as-is) in a commercial and closed-source application?

**Comment by sanjayaksaxena** [comment]
Hello @chadkirby 

You are welcome to use `wink-bm25-text-search` along with other `wink` npm packages on an "**as-is**" basis in any **commercial closed-source** application. There are no restrictions on that and  **you are not required to make your source code as "open source" at any point.**

Our motivation of keeping it under AGPL is to encourage users to open source any modifications that they may want to make in `wink-bm25-text-search` source code; so that those changes are also available to the community members like yourself! Therefore, if you choose to enhance/modify `wink-bm25-text-search`, we do expect you to make those changes available in open source so that the community can benefit from them!

If you are planning to modify `wink-bm25-text-search`, consider contributing to this project and help the open source community grow!

Best,
Sanjaya

**Comment by chadkirby** [comment]
Thanks.
